# Generated by Django 3.2.17 on 2023-03-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerHome', '0007_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_license',
        ),
    ]
