# Generated by Django 3.2.17 on 2023-04-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerHome', '0009_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
